export const ActionType = {
  User: {
    GET_CURRENT_USER_REQUEST: 'GET_CURRENT_USER_REQUEST',
    GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
    GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',
  },
  Player: {
    GET_ALL_PLAYERS_REQUEST: 'GET_ALL_PLAYERS_REQUEST',
    GET_ALL_PLAYERS_SUCCESS: 'GET_ALL_PLAYERS_SUCCESS',
    GET_ALL_PLAYERS_FAILURE: 'GET_ALL_PLAYERS_FAILURE',

    GET_ACTIVE_PLAYERS_REQUEST: 'GET_ACTIVE_PLAYERS_REQUEST',
    GET_ACTIVE_PLAYERS_SUCCESS: 'GET_ACTIVE_PLAYERS_SUCCESS',
    GET_ACTIVE_PLAYERS_FAILURE: 'GET_ACTIVE_PLAYERS_FAILURE',

    GET_PLAYER_REQUEST: 'GET_PLAYER_REQUEST',
    GET_PLAYER_SUCCESS: 'GET_PLAYER_SUCCESS',
    GET_PLAYER_FAILURE: 'GET_PLAYER_FAILURE',

    APPEND_TO_PLAYERS_REQUEST: 'APPEND_TO_PLAYERS_REQUEST',
    APPEND_TO_PLAYERS_SUCCESS: 'APPEND_TO_PLAYERS_SUCCESS',
    APPEND_TO_PLAYERS_FAILURE: 'APPEND_TO_PLAYERS_FAILURE',

    APPEND_TO_ACTIVE_PLAYERS_REQUEST: 'APPEND_TO_ACTIVE_PLAYERS_REQUEST',
    APPEND_TO_ACTIVE_PLAYERS_SUCCESS: 'APPEND_TO_ACTIVE_PLAYERS_SUCCESS',
    APPEND_TO_ACTIVE_PLAYERS_FAILURE: 'APPEND_TO_ACTIVE_PLAYERS_FAILURE',

    GET_PLAYERS_DASHBOARD_REQUEST: 'GET_PLAYERS_DASHBOARD_REQUEST',
    GET_PLAYERS_DASHBOARD_SUCCESS: 'GET_PLAYERS_DASHBOARD_SUCCESS',
    GET_PLAYERS_DASHBOARD_FAILURE: 'GET_PLAYERS_DASHBOARD_FAILURE',

    GET_PLAYER_DELTA_STATISTIC_REQUEST: 'GET_PLAYER_DELTA_STATISTIC_REQUEST',
    GET_PLAYER_DELTA_STATISTIC_SUCCESS: 'GET_PLAYER_DELTA_STATISTIC_SUCCESS',
    GET_PLAYER_DELTA_STATISTIC_FAILURE: 'GET_PLAYER_DELTA_STATISTIC_FAILURE',

    GET_PLAYER_GAMES_COUNT_STATISTIC_REQUEST: 'GET_PLAYER_GAMES_COUNT_STATISTIC_REQUEST',
    GET_PLAYER_GAMES_COUNT_STATISTIC_SUCCESS: 'GET_PLAYER_GAMES_COUNT_STATISTIC_SUCCESS',
    GET_PLAYER_GAMES_COUNT_STATISTIC_FAILURE: 'GET_PLAYER_GAMES_COUNT_STATISTIC_FAILURE',

    GET_RELATIONS_REQUEST: 'GET_RELATIONS_REQUEST',
    GET_RELATIONS_SUCCESS: 'GET_RELATIONS_SUCCESS',
    GET_RELATIONS_FAILURE: 'GET_RELATIONS_FAILURE',

    GET_RELATIONS_DASHBOARD_REQUEST: 'GET_RELATIONS_DASHBOARD_REQUEST',
    GET_RELATIONS_DASHBOARD_SUCCESS: 'GET_RELATIONS_DASHBOARD_SUCCESS',
    GET_RELATIONS_DASHBOARD_FAILURE: 'GET_RELATIONS_DASHBOARD_FAILURE',

    GET_SEARCH_RESULT_REQUEST: 'GET_SEARCH_RESULT_REQUEST',
    GET_SEARCH_RESULT_SUCCESS: 'GET_SEARCH_RESULT_SUCCESS',
    GET_SEARCH_RESULT_FAILURE: 'GET_SEARCH_RESULT_FAILURE',

    GET_PLAYER_ACHIEVEMENTS_REQUEST: 'GET_PLAYER_ACHIEVEMENTS_REQUEST',
    GET_PLAYER_ACHIEVEMENTS_SUCCESS: 'GET_PLAYER_ACHIEVEMENTS_SUCCESS',
    GET_PLAYER_ACHIEVEMENTS_FAILURE: 'GET_PLAYER_ACHIEVEMENTS_FAILURE',

    INIT_SORT: 'INIT_SORT',
  },
  Game: {
    GET_ALL_GAMES_REQUEST: 'GET_ALL_GAMES_REQUEST',
    GET_ALL_GAMES_SUCCESS: 'GET_ALL_GAMES_SUCCESS',
    GET_ALL_GAMES_FAILURE: 'GET_ALL_GAMES_FAILURE',

    GET_LATEST_GAMES_REQUEST: 'GET_LATEST_GAMES_REQUEST',
    GET_LATEST_GAMES_SUCCESS: 'GET_LATEST_GAMES_SUCCESS',
    GET_LATEST_GAMES_FAILURE: 'GET_LATEST_GAMES_FAILURE',

    GET_LAST_GAME_REQUEST: 'GET_LAST_GAME_REQUEST',
    GET_LAST_GAME_SUCCESS: 'GET_LAST_GAME_SUCCESS',
    GET_LAST_GAME_FAILURE: 'GET_LAST_GAME_FAILURE',

    GET_PLAYER_GAMES_REQUEST: 'GET_PLAYER_GAMES_REQUEST',
    GET_PLAYER_GAMES_SUCCESS: 'GET_PLAYER_GAMES_SUCCESS',
    GET_PLAYER_GAMES_FAILURE: 'GET_PLAYER_GAMES_FAILURE',

    APPEND_TO_GAMES_REQUEST: 'APPEND_TO_GAMES_REQUEST',
    APPEND_TO_GAMES_SUCCESS: 'APPEND_TO_GAMES_SUCCESS',
    APPEND_TO_GAMES_FAILURE: 'APPEND_TO_GAMES_FAILURE',

    APPEND_TO_PLAYER_GAMES_REQUEST: 'APPEND_TO_PLAYER_GAMES_REQUEST',
    APPEND_TO_PLAYER_GAMES_SUCCESS: 'APPEND_TO_PLAYER_GAMES_SUCCESS',
    APPEND_TO_PLAYER_GAMES_FAILURE: 'APPEND_TO_PLAYER_GAMES_FAILURE',

    GET_GAMES_COUNT_PER_WEEK_REQUEST: 'GET_GAMES_COUNT_PER_WEEK_REQUEST',
    GET_GAMES_COUNT_PER_WEEK_SUCCESS: 'GET_GAMES_COUNT_PER_WEEK_SUCCESS',
    GET_GAMES_COUNT_PER_WEEK_FAILURE: 'GET_GAMES_COUNT_PER_WEEK_FAILURE',
  }
};
