export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE';

export const GET_ALL_PLAYERS_REQUEST = 'GET_ALL_PLAYERS_REQUEST';
export const GET_ALL_PLAYERS_SUCCESS = 'GET_ALL_PLAYERS_SUCCESS';
export const GET_ALL_PLAYERS_FAILURE = 'GET_ALL_PLAYERS_FAILURE';

export const GET_ACTIVE_PLAYERS_REQUEST = 'GET_ACTIVE_PLAYERS_REQUEST';
export const GET_ACTIVE_PLAYERS_SUCCESS = 'GET_ACTIVE_PLAYERS_SUCCESS';
export const GET_ACTIVE_PLAYERS_FAILURE = 'GET_ACTIVE_PLAYERS_FAILURE';

export const GET_PLAYER_REQUEST = 'GET_PLAYER_REQUEST';
export const GET_PLAYER_SUCCESS = 'GET_PLAYER_SUCCESS';
export const GET_PLAYER_FAILURE = 'GET_PLAYER_FAILURE';

// export const REGISTER_GAME_REQUEST = 'REGISTER_GAME_REQUEST';
// export const REGISTER_GAME_SUCCESS = 'REGISTER_GAME_SUCCESS';
// export const REGISTER_GAME_FAILURE = 'REGISTER_GAME_FAILURE';